### ISSUE TITLE
Update jbcrypt to v0.4

### ISSUE THREAD

**Issue by boughtonp** [boughtonp/cfpassphrase#16]

**Comment by JamoCA** [comment]
I was reviewing this library for use with Adobe ColdFusion and noticed that the jBcrypt library needed to be upgraded as well.

**Comment by boughtonp** [comment]
The difference between jBcrypt 0.3 and 0.4 is a limit of 30 for log_rounds (down from 31) to prevent integer overflow - so it's ok to use the current version if you enforce this limit yourself.

I'll try to address this soon though.

**Comment by JamoCA** [comment]
Thanks for the quick response (and for this consolidated library.)

What about scrypt? Which version is used? 1.1.6?  If so, it looks like a fair amount of updates were pushed for the 1.2.0 update on 7/30/2015.
https://github.com/Tarsnap/scrypt/compare/1.1.6...master

**Comment by boughtonp** [comment]
It's the [Java implementation of scrypt](https://github.com/wg/scrypt), and yeah I think that's still equivalent to 1.1.6

I've added issue #17 to check this out, since I suspect it'll involve more work than updating jBcrypt.

**Comment by boughtonp** [comment]
Release of cfPassphrase v0.2 includes jBCrypt 0.4
