### ISSUE TITLE
Incorrect Link in documentation

### ISSUE THREAD

**Issue by andrew-dixon** [boughtonp/cfpassphrase#22]
On this page:

https://docs.sorcerersisle.com/cfpassphrase/

The link to the `PassphraseCheck` doc page links to:

https://docs.sorcerersisle.com/cfpassphrase/functions/PassphraseHash

Instead of:

https://docs.sorcerersisle.com/cfpassphrase/functions/PassphraseCheck

**Comment by boughtonp** [comment]
Thanks Andrew, not sure how that happened, but it's fixed now.
